"""项目结构说明生成 — 基于 repo_summary.json 输出 STRUCTURE.md。

纯确定性生成，所有内容均可追溯到 repo_summary.json 中的数据。
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

from reposcope.storage.repo_summary import RepoSummary


def generate_structure_md(summary: RepoSummary) -> str:
    """生成 STRUCTURE.md 的完整 Markdown 文本。

    Args:
        summary: 预分析的 RepoSummary

    Returns:
        STRUCTURE.md 的 Markdown 字符串
    """
    repo_name = os.path.basename(summary.repo_path.rstrip(os.sep)) or "project"
    lines: list[str] = []

    _header(lines, repo_name)
    _overview(lines, summary)
    _entry_points(lines, summary)
    _module_roles(lines, summary)
    _topological_layers(lines, summary)
    _structural_core(lines, summary)
    _circular_deps(lines, summary)
    _key_dependencies(lines, summary)
    _file_inventory(lines, summary)
    _footer(lines)

    return "\n".join(lines)


def save_structure_md(summary: RepoSummary, output_path: str) -> str:
    """生成并保存 STRUCTURE.md 文件。

    Returns:
        写入的文件路径
    """
    content = generate_structure_md(summary)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path


# ---------------------------------------------------------------------------
# 各章节生成
# ---------------------------------------------------------------------------

def _header(lines: list[str], repo_name: str) -> None:
    lines.append(f"# Project Structure — {repo_name}")
    lines.append("")
    lines.append(
        "> Auto-generated by [RepoScope Agent](https://github.com) "
        f"on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append("")
    lines.append(
        "This document provides a deterministic, evidence-based overview "
        "of the project's internal module structure. "
        "Every claim can be traced back to `repo_summary.json`."
    )
    lines.append("")


def _overview(lines: list[str], s: RepoSummary) -> None:
    """项目概览表格。"""
    lines.append("## 1. Overview")
    lines.append("")
    dag = "Yes" if s.is_dag else f"No ({len(s.circular_deps)} cycle(s))"
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Repository path | `{s.repo_path}` |")
    lines.append(f"| Python files | {s.python_file_count} |")
    lines.append(f"| Files scanned | {s.total_files_scanned} |")
    lines.append(f"| Files skipped | {s.skipped_file_count} |")
    lines.append(f"| Module nodes | {s.module_count} |")
    lines.append(f"| Internal dependency edges | {s.edge_count} |")
    lines.append(f"| Total imports | {s.total_imports} "
                 f"(internal: {s.internal_imports}, "
                 f"external: {s.external_imports}, "
                 f"unknown: {s.unknown_imports}) |")
    lines.append(f"| Classes defined | {s.total_classes} |")
    lines.append(f"| Functions defined | {s.total_functions} |")
    lines.append(f"| Files with `__main__` guard | {len(s.files_with_main_guard)} |")
    lines.append(f"| Is DAG | {dag} |")
    lines.append(f"| Topological depth | {s.depth} layers |")
    lines.append("")

    # Skip reason summary
    if s.skipped_reason_counts:
        lines.append("### Skip Reasons")
        lines.append("")
        lines.append("| Reason | Count |")
        lines.append("|---|---|")
        for reason, count in sorted(s.skipped_reason_counts.items(), key=lambda x: -x[1]):
            lines.append(f"| {reason} | {count} |")
        lines.append("")


def _entry_points(lines: list[str], s: RepoSummary) -> None:
    """入口候选。"""
    lines.append("## 2. Entry Points")
    lines.append("")
    if not s.entry_candidates:
        lines.append("No entry point candidates detected.")
        lines.append("")
        return

    lines.append(
        "Entry candidates are identified by multiple signals: "
        "`__main__` guard, root module status (no incoming edges), "
        "high out-degree, and naming conventions."
    )
    lines.append("")
    lines.append("| # | Module | Score | Signals |")
    lines.append("|---|---|---|---|")
    for i, e in enumerate(s.entry_candidates, 1):
        lines.append(
            f"| {i} | `{e['module']}` | {e['score']:.2f} | "
            f"{', '.join(e['signals'])} |"
        )
    lines.append("")


def _module_roles(lines: list[str], s: RepoSummary) -> None:
    """模块角色分类。"""
    lines.append("## 3. Module Roles")
    lines.append("")
    lines.append(
        "Each module is assigned a role based on its structural characteristics "
        "(imports, exports, classes, functions, `__main__` guard)."
    )
    lines.append("")

    cats = s.module_categories
    by_role: dict[str, list[str]] = {}
    for module, role in sorted(cats.items()):
        by_role.setdefault(role, []).append(module)

    role_descriptions = {
        "entry": "Has `__main__` guard; likely a runnable script",
        "orchestrator": "Imports many internal modules; coordinates others",
        "model": "Defines classes; likely data or domain models",
        "utility": "Imported by 2+ modules; provides shared functions",
        "package_init": "`__init__.py`; re-exports submodules",
        "config": "No classes, functions, or internal imports",
        "leaf": "No internal imports; end of dependency chain",
        "module": "Generic module",
    }

    role_order = ["entry", "orchestrator", "model", "utility",
                   "package_init", "config", "leaf", "module"]

    for role in role_order:
        modules = by_role.pop(role, [])
        if not modules:
            continue
        desc = role_descriptions.get(role, "")
        lines.append(f"### {role} ({len(modules)})")
        if desc:
            lines.append(f"_{desc}_")
        lines.append("")
        for m in modules:
            label = m if m else "(root `__init__.py`)"
            lines.append(f"- `{label}`")
        lines.append("")

    # 剩余未排序角色
    for role, modules in sorted(by_role.items()):
        if not modules:
            continue
        lines.append(f"### {role} ({len(modules)})")
        lines.append("")
        for m in modules:
            lines.append(f"- `{m if m else '(root __init__.py)'}`")
        lines.append("")


def _topological_layers(lines: list[str], s: RepoSummary) -> None:
    """拓扑分层。"""
    lines.append("## 4. Dependency Layers (Topological)")
    lines.append("")
    lines.append(
        "Modules are grouped into layers by their position in the dependency chain. "
        "Layer 0 modules have no internal dependencies; "
        "higher layers depend on lower layers."
    )
    lines.append("")

    for i, layer in enumerate(s.layers):
        label = "Foundation (no internal deps)" if i == 0 else f"Layer {i}"
        lines.append(f"### {label}")
        lines.append("")
        for node in layer:
            role = s.module_categories.get(node, "-")
            node_label = node if node else "(root `__init__.py`)"
            lines.append(f"- `{node_label}` _{role}_")
        lines.append("")


def _structural_core(lines: list[str], s: RepoSummary) -> None:
    """结构核心模块候选。"""
    lines.append("## 5. Structural Core Candidates")
    lines.append("")
    lines.append(
        "Ranked by **structural importance** in the import graph "
        "(composite score = 0.4×in-degree + 0.3×betweenness + 0.3×PageRank). "
        "These are NOT necessarily the business-logic core — "
        "they are modules that hold the dependency graph together."
    )
    lines.append("")

    if not s.structural_core_candidates:
        lines.append("No structural core candidates.")
        lines.append("")
        return

    lines.append("| # | Module | Score | Imported By | Role |")
    lines.append("|---|---|---|---|---|")
    for i, c in enumerate(s.structural_core_candidates, 1):
        role = s.module_categories.get(c["module"], "-")
        lines.append(
            f"| {i} | `{c['module']}` | {c['score']:.3f} | "
            f"{c['in_degree']} | {role} |"
        )
    lines.append("")


def _circular_deps(lines: list[str], s: RepoSummary) -> None:
    """循环依赖。"""
    lines.append("## 6. Circular Dependencies")
    lines.append("")
    if not s.circular_deps:
        lines.append("None detected. The dependency graph is a **DAG** "
                      "(directed acyclic graph).")
        lines.append("")
        return

    lines.append(f"**{len(s.circular_deps)} cycle(s) detected:**")
    lines.append("")
    for i, cycle in enumerate(s.circular_deps, 1):
        chain = " → ".join(cycle)
        lines.append(f"{i}. `{chain}` → `{cycle[0]}`")
    lines.append("")
    lines.append(
        "Circular dependencies can make code harder to understand, test, "
        "and refactor. Consider breaking cycles through dependency inversion "
        "or extracting shared interfaces."
    )
    lines.append("")


def _key_dependencies(lines: list[str], s: RepoSummary) -> None:
    """关键依赖关系摘要（高扇出 + 高扇入模块）。"""
    g_data = s.graph_data
    nodes = {n["id"]: n for n in g_data.get("nodes", [])}
    links = g_data.get("links", [])

    # 计算入度/出度
    in_deg: dict[str, int] = {}
    out_deg: dict[str, int] = {}
    for link in links:
        src = link["source"]
        tgt = link["target"]
        out_deg[src] = out_deg.get(src, 0) + 1
        in_deg[tgt] = in_deg.get(tgt, 0) + 1

    # 高扇出模块（导入很多内部模块）
    high_out = sorted(out_deg.items(), key=lambda x: -x[1])
    high_in = sorted(in_deg.items(), key=lambda x: -x[1])

    if high_out:
        lines.append("## 7. Key Dependency Relationships")
        lines.append("")

        lines.append("### Most Internal Imports (high out-degree)")
        lines.append("")
        lines.append("| Module | Imports |")
        lines.append("|---|---|")
        for mod, deg in high_out[:5]:
            lines.append(f"| `{mod}` | {deg} |")
        lines.append("")

    if high_in:
        lines.append("### Most Imported (high in-degree)")
        lines.append("")
        lines.append("| Module | Imported By |")
        lines.append("|---|---|")
        for mod, deg in high_in[:5]:
            lines.append(f"| `{mod}` | {deg} |")
        lines.append("")


def _file_inventory(lines: list[str], s: RepoSummary) -> None:
    """文件清单（折叠区）。"""
    lines.append("## 8. File Inventory")
    lines.append("")
    lines.append(
        f"<details>\n<summary>All Python files ({s.python_file_count})</summary>\n"
    )
    lines.append("| # | File | Module | Role |")
    lines.append("|---|---|---|---|")
    for i, f in enumerate(s.python_files, 1):
        # 从 node data 中查找对应模块名
        module = ""
        role = ""
        for node in s.graph_data.get("nodes", []):
            if node.get("file_path") == f:
                module = node.get("id", "")
                role = s.module_categories.get(module, "")
                break
        lines.append(f"| {i} | `{f}` | `{module}` | {role} |")
    lines.append("")
    lines.append("</details>")
    lines.append("")


def _footer(lines: list[str]) -> None:
    lines.append("")
    lines.append("---")
    lines.append(
        "*This document was generated deterministically by RepoScope Agent. "
        "No LLM was used in its creation.*"
    )
